/**
 * Korean typed into xterm 5.5 on macOS, as WebKit actually delivered it.
 *
 * Recorded in the real NexTerm dev app (WKWebView, macOS 26.6, the 2-Set
 * Korean input source, real keystrokes posted to the app) by a capture-phase
 * recorder on xterm's helper textarea, plus xterm's own `onData` — what the
 * shell was sent. The three `t_c_safari_*` streams are the same keys typed
 * into xterm 5.5 in Safari, where the IME switched to ordinary composition
 * events. Only the textarea's events are kept, in the order they arrived.
 *
 * One row per event:
 *
 *   ['bi'|'in', inputType, data, value, selectionStart, selectionEnd, composing?]
 *        beforeinput / input, with the textarea as it was at that moment —
 *        for beforeinput before the change, for input after it. inputType:
 *        IT insertText, IRT insertReplacementText, ICT insertCompositionText,
 *        DCT deleteCompositionText, IFC insertFromComposition.
 *   ['kd'|'ku'|'kp', key, keyCode, code, modifiers?, composing?]
 *        keydown / keyup / keypress; modifiers is any of s c a m
 *        (shift ctrl alt meta).
 *   ['cs'|'cu'|'ce', data, value, selectionStart, selectionEnd]
 *        compositionstart / update / end.
 *   ['blur'|'focus', value, selectionStart, selectionEnd]
 *        the textarea losing or regaining focus.
 *   ['sent', data]
 *        what xterm 5.5 sent to the shell at that point, today. Not an event.
 *   ['xterm', 'keyDownSeen']
 *        state xterm carried in from the recording before. Not an event.
 *
 * The scenarios ran one after another into the same textarea, so most begin
 * with the previous ones' text in it; where no event reaches into that text it
 * is cut off, with every position moved by the same amount. `s01_hangul_space`
 * is kept whole for a different reason: the IME was still composing `글` from
 * the run before, and the stream begins by rewriting it.
 */
export const RECORDINGS = {
  // s01_hangul_space.json — IME still composing 글 from the previous run (first 1 characters of the textarea cut)
  s01_hangul_space: [
    ['bi', 'IRT', '긇', '글', 0, 1],
    ['in', 'IRT', '긇', '긇', 1, 1],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '글', '긇', 0, 1],
    ['in', 'IRT', '글', '글', 1, 1],
    ['bi', 'IT', '하', '글', 1, 1],
    ['in', 'IT', '하', '글하', 2, 2],
    ['sent', '하'],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '글하', 1, 2],
    ['in', 'IRT', '한', '글한', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '글한', 1, 2],
    ['in', 'IRT', '한', '글한', 2, 2],
    ['bi', 'IT', 'ㄱ', '글한', 2, 2],
    ['in', 'IT', 'ㄱ', '글한ㄱ', 3, 3],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', '그', '글한ㄱ', 2, 3],
    ['in', 'IRT', '그', '글한그', 3, 3],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['bi', 'IRT', '글', '글한그', 2, 3],
    ['in', 'IRT', '글', '글한글', 3, 3],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['bi', 'IRT', '글', '글한글', 2, 3],
    ['in', 'IRT', '글', '글한글', 3, 3],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '글한글', 3, 3],
    ['in', 'IT', ' ', '글한글\u00a0', 4, 4],
    ['ku', ' ', 32, 'Space'],
  ],
  // t_nexterm_after_safari.json — the same keys with a fresh textarea
  s01_clean_hangul_space: [
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '한', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['bi', 'IT', 'ㄱ', '한', 1, 1],
    ['in', 'IT', 'ㄱ', '한ㄱ', 2, 2],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', '그', '한ㄱ', 1, 2],
    ['in', 'IRT', '그', '한그', 2, 2],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['bi', 'IRT', '글', '한그', 1, 2],
    ['in', 'IRT', '글', '한글', 2, 2],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['bi', 'IRT', '글', '한글', 1, 2],
    ['in', 'IRT', '글', '한글', 2, 2],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '한글', 2, 2],
    ['in', 'IT', ' ', '한글\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
  ],
  // s02_annyeong_enter.json (first 4 characters of the textarea cut)
  s02_annyeong_enter: [
    ['bi', 'IT', 'ㅇ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅇ', ' ㅇ', 2, 2],
    ['sent', 'ㅇ'],
    ['kd', 'ㅇ', 229, 'KeyD'],
    ['ku', 'ㅇ', 68, 'KeyD'],
    ['bi', 'IRT', '아', ' ㅇ', 1, 2],
    ['in', 'IRT', '아', ' 아', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '안', ' 아', 1, 2],
    ['in', 'IRT', '안', ' 안', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '안', ' 안', 1, 2],
    ['in', 'IRT', '안', ' 안', 2, 2],
    ['bi', 'IT', 'ㄴ', ' 안', 2, 2],
    ['in', 'IT', 'ㄴ', ' 안ㄴ', 3, 3],
    ['sent', 'ㄴ'],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '녀', ' 안ㄴ', 2, 3],
    ['in', 'IRT', '녀', ' 안녀', 3, 3],
    ['kd', 'ㅕ', 229, 'KeyU'],
    ['ku', 'ㅕ', 85, 'KeyU'],
    ['bi', 'IRT', '녕', ' 안녀', 2, 3],
    ['in', 'IRT', '녕', ' 안녕', 3, 3],
    ['kd', 'ㅇ', 229, 'KeyD'],
    ['ku', 'ㅇ', 68, 'KeyD'],
    ['bi', 'IRT', '녕', ' 안녕', 2, 3],
    ['in', 'IRT', '녕', ' 안녕', 3, 3],
    ['bi', 'IT', 'ㅎ', ' 안녕', 3, 3],
    ['in', 'IT', 'ㅎ', ' 안녕ㅎ', 4, 4],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', ' 안녕ㅎ', 3, 4],
    ['in', 'IRT', '하', ' 안녕하', 4, 4],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '핫', ' 안녕하', 3, 4],
    ['in', 'IRT', '핫', ' 안녕핫', 4, 4],
    ['kd', 'ㅅ', 229, 'KeyT'],
    ['ku', 'ㅅ', 84, 'KeyT'],
    ['bi', 'IRT', '하', ' 안녕핫', 3, 4],
    ['in', 'IRT', '하', ' 안녕하', 4, 4],
    ['bi', 'IT', '세', ' 안녕하', 4, 4],
    ['in', 'IT', '세', ' 안녕하세', 5, 5],
    ['sent', '세'],
    ['kd', 'ㅔ', 229, 'KeyP'],
    ['ku', 'ㅔ', 80, 'KeyP'],
    ['bi', 'IRT', '셍', ' 안녕하세', 4, 5],
    ['in', 'IRT', '셍', ' 안녕하셍', 5, 5],
    ['kd', 'ㅇ', 229, 'KeyD'],
    ['ku', 'ㅇ', 68, 'KeyD'],
    ['bi', 'IRT', '세', ' 안녕하셍', 4, 5],
    ['in', 'IRT', '세', ' 안녕하세', 5, 5],
    ['bi', 'IT', '요', ' 안녕하세', 5, 5],
    ['in', 'IT', '요', ' 안녕하세요', 6, 6],
    ['sent', '요'],
    ['kd', 'ㅛ', 229, 'KeyY'],
    ['ku', 'ㅛ', 89, 'KeyY'],
    ['bi', 'IRT', '요', ' 안녕하세요', 5, 6],
    ['in', 'IRT', '요', ' 안녕하세요', 6, 6],
    ['kd', 'Enter', 13, 'Enter'],
    ['sent', '\x0d'],
    ['ku', 'Enter', 13, 'Enter'],
  ],
  // s03_gana_tab.json
  s03_gana_tab: [
    ['bi', 'IT', 'ㄱ', '', 0, 0],
    ['in', 'IT', 'ㄱ', 'ㄱ', 1, 1],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', '가', 'ㄱ', 0, 1],
    ['in', 'IRT', '가', '가', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '간', '가', 0, 1],
    ['in', 'IRT', '간', '간', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '가', '간', 0, 1],
    ['in', 'IRT', '가', '가', 1, 1],
    ['bi', 'IT', '나', '가', 1, 1],
    ['in', 'IT', '나', '가나', 2, 2],
    ['sent', '나'],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['kd', 'Tab', 9, 'Tab'],
    ['sent', '\x09'],
    ['ku', 'Tab', 9, 'Tab'],
  ],
  // s04_kka_dot.json (first 2 characters of the textarea cut)
  s04_kka_dot: [
    ['kd', 'Shift', 16, 'ShiftLeft', 's'],
    ['ku', 'Shift', 16, 'ShiftLeft'],
    ['ku', 'ㄲ', 82, 'KeyR', 's'],
    ['bi', 'IT', 'ㄲ', '', 0, 0],
    ['in', 'IT', 'ㄲ', 'ㄲ', 1, 1],
    ['sent', 'ㄲ'],
    ['kd', 'ㄲ', 229, 'KeyR', 's'],
    ['bi', 'IRT', '까', 'ㄲ', 0, 1],
    ['in', 'IRT', '까', '까', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '까', '까', 0, 1],
    ['in', 'IRT', '까', '까', 1, 1],
    ['kd', '.', 190, 'Period'],
    ['sent', '.'],
    ['ku', '.', 190, 'Period'],
  ],
  // s05_wa_digit.json (first 3 characters of the textarea cut)
  s05_wa_digit: [
    ['bi', 'IT', 'ㅇ', '', 0, 0],
    ['in', 'IT', 'ㅇ', 'ㅇ', 1, 1],
    ['sent', 'ㅇ'],
    ['kd', 'ㅇ', 229, 'KeyD'],
    ['ku', 'ㅇ', 68, 'KeyD'],
    ['bi', 'IRT', '오', 'ㅇ', 0, 1],
    ['in', 'IRT', '오', '오', 1, 1],
    ['kd', 'ㅗ', 229, 'KeyH'],
    ['ku', 'ㅗ', 72, 'KeyH'],
    ['bi', 'IRT', '와', '오', 0, 1],
    ['in', 'IRT', '와', '와', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['ku', '1', 49, 'Digit1'],
    ['bi', 'IRT', '와', '와', 0, 1],
    ['in', 'IRT', '와', '와', 1, 1],
    ['kd', '1', 49, 'Digit1'],
    ['sent', '1'],
  ],
  // s06_eops_esc.json (first 4 characters of the textarea cut)
  s06_eops_esc: [
    ['ku', 'ㅇ', 68, 'KeyD'],
    ['bi', 'IT', 'ㅇ', '', 0, 0],
    ['in', 'IT', 'ㅇ', 'ㅇ', 1, 1],
    ['sent', 'ㅇ'],
    ['kd', 'ㅇ', 229, 'KeyD'],
    ['bi', 'IRT', '어', 'ㅇ', 0, 1],
    ['in', 'IRT', '어', '어', 1, 1],
    ['kd', 'ㅓ', 229, 'KeyJ'],
    ['ku', 'ㅓ', 74, 'KeyJ'],
    ['bi', 'IRT', '업', '어', 0, 1],
    ['in', 'IRT', '업', '업', 1, 1],
    ['kd', 'ㅂ', 229, 'KeyQ'],
    ['ku', 'ㅂ', 81, 'KeyQ'],
    ['bi', 'IRT', '없', '업', 0, 1],
    ['in', 'IRT', '없', '없', 1, 1],
    ['kd', 'ㅅ', 229, 'KeyT'],
    ['ku', 'ㅅ', 84, 'KeyT'],
    ['bi', 'IRT', '없', '없', 0, 1],
    ['in', 'IRT', '없', '없', 1, 1],
    ['kd', 'Escape', 27, 'Escape'],
    ['sent', '\x1b'],
    ['ku', 'Escape', 27, 'Escape'],
  ],
  // s07_han_left.json (first 5 characters of the textarea cut)
  s07_han_left: [
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '한', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ArrowLeft', 37, 'ArrowLeft'],
    ['sent', '\x1b[D'],
    ['ku', 'ArrowLeft', 37, 'ArrowLeft'],
  ],
  // s08_han_right.json (first 6 characters of the textarea cut)
  s08_han_right: [
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '한', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ArrowRight', 39, 'ArrowRight'],
    ['sent', '\x1b[C'],
    ['ku', 'ArrowRight', 39, 'ArrowRight'],
  ],
  // s09_bs_mid.json (first 7 characters of the textarea cut)
  s09_bs_mid: [
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '하', '한', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'Backspace', 229, 'Backspace'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['bi', 'IRT', 'ㅎ', '하', 0, 1],
    ['in', 'IRT', 'ㅎ', 'ㅎ', 1, 1],
    ['kd', 'Backspace', 229, 'Backspace'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['bi', 'IRT', 'ㅎ', 'ㅎ', 0, 1],
    ['in', 'IRT', 'ㅎ', 'ㅎ', 1, 1],
    ['kd', 'Backspace', 8, 'Backspace'],
    ['sent', '\x7f'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['kd', 'Backspace', 8, 'Backspace'],
    ['sent', '\x7f'],
    ['ku', 'Backspace', 8, 'Backspace'],
  ],
  // s10_bs_after.json (first 8 characters of the textarea cut)
  s10_bs_after: [
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '한', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['bi', 'IT', 'ㄱ', '한', 1, 1],
    ['in', 'IT', 'ㄱ', '한ㄱ', 2, 2],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', 'ㄱ', '한ㄱ', 1, 2],
    ['in', 'IRT', 'ㄱ', '한ㄱ', 2, 2],
    ['kd', 'Backspace', 8, 'Backspace'],
    ['sent', '\x7f'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['kd', 'Backspace', 8, 'Backspace'],
    ['sent', '\x7f'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['kd', 'Backspace', 8, 'Backspace'],
    ['sent', '\x7f'],
    ['ku', 'Backspace', 8, 'Backspace'],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '한ㄱ', 2, 2],
    ['in', 'IT', ' ', '한ㄱ\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
  ],
  // s11_han_ctrlc.json (first 5 characters of the textarea cut)
  s11_han_ctrlc: [
    ['bi', 'IT', 'ㅎ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅎ', ' ㅎ', 2, 2],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '하', ' ㅎ', 1, 2],
    ['in', 'IRT', '하', ' 하', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['bi', 'IRT', '한', ' 하', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['kd', 'Control', 17, 'ControlLeft', 'c'],
    ['ku', 'Control', 17, 'ControlLeft'],
    ['ku', 'ㅊ', 67, 'KeyC', 'c'],
    ['bi', 'IRT', '한', ' 한', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['kd', 'ㅊ', 67, 'KeyC', 'c'],
    ['sent', '\x03'],
  ],
  // s12a_ctrlspace_switch.json (first 1 characters of the textarea cut)
  s12a_ctrlspace_switch: [
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IT', 'ㅎ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅎ', ' ㅎ', 2, 2],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['bi', 'IRT', '하', ' ㅎ', 1, 2],
    ['in', 'IRT', '하', ' 하', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['kd', 's', 83, 'KeyS'],
    ['sent', 's'],
    ['ku', 's', 83, 'KeyS'],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', ' 하', 2, 2],
    ['in', 'IT', ' ', ' 하\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
    ['bi', 'IT', 'ㄴ', ' 하\u00a0', 3, 3],
    ['in', 'IT', 'ㄴ', ' 하 ㄴ', 4, 4],
    ['sent', 'ㄴ'],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', 'ㄴ', ' 하 ㄴ', 3, 4],
    ['in', 'IRT', 'ㄴ', ' 하 ㄴ', 4, 4],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', ' 하 ㄴ', 4, 4],
    ['in', 'IT', ' ', ' 하 ㄴ\u00a0', 5, 5],
    ['ku', ' ', 32, 'Space'],
  ],
  // s13_deactivate.json
  s13_deactivate: [
    ['bi', 'IT', 'ㅎ', '가나까와없한한ㅎ한ㄱ 한글 한글\u00a0', 17, 17],
    ['in', 'IT', 'ㅎ', '가나까와없한한ㅎ한ㄱ 한글 한글 ㅎ', 18, 18],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', '가나까와없한한ㅎ한ㄱ 한글 한글 ㅎ', 17, 18],
    ['in', 'IRT', '하', '가나까와없한한ㅎ한ㄱ 한글 한글 하', 18, 18],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['blur', '가나까와없한한ㅎ한ㄱ 한글 한글 하', 18, 18],
    ['focus', '', 0, 0],
    ['bi', 'IT', 'ㄴ', '', 0, 0],
    ['in', 'IT', 'ㄴ', 'ㄴ', 1, 1],
    ['sent', 'ㄴ'],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', 'ㄴ', 'ㄴ', 0, 1],
    ['in', 'IRT', 'ㄴ', 'ㄴ', 1, 1],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', 'ㄴ', 1, 1],
    ['in', 'IT', ' ', 'ㄴ\u00a0', 2, 2],
    ['ku', ' ', 32, 'Space'],
  ],
  // s14_focus_elsewhere.json
  s14_focus_elsewhere: [
    ['bi', 'IT', 'ㅎ', 'ㄴ\u00a0', 2, 2],
    ['in', 'IT', 'ㅎ', 'ㄴ ㅎ', 3, 3],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㄴ ㅎ', 2, 3],
    ['in', 'IRT', '하', 'ㄴ 하', 3, 3],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['blur', 'ㄴ 하', 3, 3],
    ['focus', '', 0, 0],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IT', 'ㄴ', '', 0, 0],
    ['in', 'IT', 'ㄴ', 'ㄴ', 1, 1],
    ['sent', 'ㄴ'],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['bi', 'IRT', 'ㄴ', 'ㄴ', 0, 1],
    ['in', 'IRT', 'ㄴ', 'ㄴ', 1, 1],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', 'ㄴ', 1, 1],
    ['in', 'IT', ' ', 'ㄴ\u00a0', 2, 2],
    ['ku', ' ', 32, 'Space'],
  ],
  // s15_fast_burst.json (first 10 characters of the textarea cut)
  s15_fast_burst: [
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IT', 'ㅎ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅎ', ' ㅎ', 2, 2],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '하', ' ㅎ', 1, 2],
    ['in', 'IRT', '하', ' 하', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['bi', 'IRT', '한', ' 하', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['bi', 'IRT', '한', ' 한', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['bi', 'IT', 'ㄱ', ' 한', 2, 2],
    ['in', 'IT', 'ㄱ', ' 한ㄱ', 3, 3],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['bi', 'IRT', '그', ' 한ㄱ', 2, 3],
    ['in', 'IRT', '그', ' 한그', 3, 3],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['bi', 'IRT', '글', ' 한그', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['ku', ' ', 32, 'Space'],
    ['bi', 'IRT', '글', ' 한글', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', ' 한글', 3, 3],
    ['in', 'IT', ' ', ' 한글\u00a0', 4, 4],
  ],
  // s16_rollover.json (first 13 characters of the textarea cut)
  s16_rollover: [
    // xterm's `_keyDownSeen` left true by s15: its last Space's keyup came before the keydown.
    ['xterm', 'keyDownSeen'],
    ['bi', 'IT', 'ㅎ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅎ', ' ㅎ', 2, 2],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['bi', 'IRT', '하', ' ㅎ', 1, 2],
    ['in', 'IRT', '하', ' 하', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '한', ' 하', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', ' 한', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['bi', 'IT', 'ㄱ', ' 한', 2, 2],
    ['in', 'IT', 'ㄱ', ' 한ㄱ', 3, 3],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '그', ' 한ㄱ', 2, 3],
    ['in', 'IRT', '그', ' 한그', 3, 3],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', '글', ' 한그', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['bi', 'IRT', '글', ' 한글', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', ' 한글', 3, 3],
    ['in', 'IT', ' ', ' 한글\u00a0', 4, 4],
    ['ku', ' ', 32, 'Space'],
  ],
  // t_busy_mainthread.json (first 2 characters of the textarea cut)
  t_busy_mainthread: [
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IT', 'ㅎ', '\u00a0', 1, 1],
    ['in', 'IT', 'ㅎ', ' ㅎ', 2, 2],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['bi', 'IRT', '하', ' ㅎ', 1, 2],
    ['in', 'IRT', '하', ' 하', 2, 2],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['ku', ' ', 32, 'Space'],
    ['bi', 'IRT', '한', ' 하', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['bi', 'IRT', '한', ' 한', 1, 2],
    ['in', 'IRT', '한', ' 한', 2, 2],
    ['bi', 'IT', 'ㄱ', ' 한', 2, 2],
    ['in', 'IT', 'ㄱ', ' 한ㄱ', 3, 3],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['bi', 'IRT', '그', ' 한ㄱ', 2, 3],
    ['in', 'IRT', '그', ' 한그', 3, 3],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['bi', 'IRT', '글', ' 한그', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['bi', 'IRT', '글', ' 한글', 2, 3],
    ['in', 'IRT', '글', ' 한글', 3, 3],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', ' 한글', 3, 3],
    ['in', 'IT', ' ', ' 한글\u00a0', 4, 4],
  ],
  // t_dom_renderer_hangul.json
  t_dom_renderer_hangul: [
    // xterm dropped the first ㅎ, so a keydown was still marked as seen from before the recording.
    ['xterm', 'keyDownSeen'],
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['bi', 'IRT', '하', 'ㅎ', 0, 1],
    ['in', 'IRT', '하', '하', 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK'],
    ['ku', 'ㅏ', 75, 'KeyK'],
    ['bi', 'IRT', '한', '하', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS'],
    ['ku', 'ㄴ', 83, 'KeyS'],
    ['bi', 'IRT', '한', '한', 0, 1],
    ['in', 'IRT', '한', '한', 1, 1],
    ['bi', 'IT', 'ㄱ', '한', 1, 1],
    ['in', 'IT', 'ㄱ', '한ㄱ', 2, 2],
    ['sent', 'ㄱ'],
    ['kd', 'ㄱ', 229, 'KeyR'],
    ['ku', 'ㄱ', 82, 'KeyR'],
    ['bi', 'IRT', '그', '한ㄱ', 1, 2],
    ['in', 'IRT', '그', '한그', 2, 2],
    ['kd', 'ㅡ', 229, 'KeyM'],
    ['ku', 'ㅡ', 77, 'KeyM'],
    ['bi', 'IRT', '글', '한그', 1, 2],
    ['in', 'IRT', '글', '한글', 2, 2],
    ['kd', 'ㄹ', 229, 'KeyF'],
    ['ku', 'ㄹ', 70, 'KeyF'],
    ['bi', 'IRT', '글', '한글', 1, 2],
    ['in', 'IRT', '글', '한글', 2, 2],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '한글', 2, 2],
    ['in', 'IT', ' ', '한글\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
  ],
  // t_c_safari_xterm.json — Safari, xterm 5.5: replacement mode, then composition events
  t_c_safari_xterm: [
    ['bi', 'IT', 'ㅎ', '', 0, 0],
    ['in', 'IT', 'ㅎ', 'ㅎ', 1, 1],
    ['sent', 'ㅎ'],
    ['kd', 'ㅎ', 229, 'KeyG'],
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['cs', '', 'ㅎ', 1, 1],
    ['cu', 'ㅏ', 'ㅎ', 1, 1],
    ['bi', 'ICT', 'ㅏ', 'ㅎ', 1, 1, 1],
    ['in', 'ICT', 'ㅏ', 'ㅎㅏ', 1, 2, 1],
    ['kd', 'ㅏ', 229, 'KeyK', '', 1],
    ['ku', 'ㅏ', 75, 'KeyK', '', 1],
    ['cu', 'ㅏ', 'ㅎㅏ', 1, 2],
    ['bi', 'ICT', 'ㅏ', 'ㅎㅏ', 1, 2, 1],
    ['in', 'ICT', 'ㅏ', 'ㅎㅏ', 1, 2, 1],
    ['bi', 'DCT', null, 'ㅎㅏ', 1, 2, 1],
    ['in', 'DCT', null, 'ㅎ', 1, 1, 1],
    ['bi', 'IFC', 'ㅏ', 'ㅎ', 1, 1, 1],
    ['in', 'IFC', 'ㅏ', 'ㅎㅏ', 2, 2, 1],
    ['ce', 'ㅏ', 'ㅎㅏ', 2, 2],
    ['sent', 'ㅏ'],
    ['cs', '', 'ㅎㅏ', 2, 2],
    ['cu', 'ㄴ', 'ㅎㅏ', 2, 2],
    ['bi', 'ICT', 'ㄴ', 'ㅎㅏ', 2, 2, 1],
    ['in', 'ICT', 'ㄴ', 'ㅎㅏㄴ', 2, 3, 1],
    ['kd', 'ㄴ', 229, 'KeyS', '', 1],
    ['ku', 'ㄴ', 83, 'KeyS', '', 1],
    ['cu', 'ㄴ', 'ㅎㅏㄴ', 2, 3],
    ['bi', 'ICT', 'ㄴ', 'ㅎㅏㄴ', 2, 3, 1],
    ['in', 'ICT', 'ㄴ', 'ㅎㅏㄴ', 2, 3, 1],
    ['bi', 'DCT', null, 'ㅎㅏㄴ', 2, 3, 1],
    ['in', 'DCT', null, 'ㅎㅏ', 2, 2, 1],
    ['bi', 'IFC', 'ㄴ', 'ㅎㅏ', 2, 2, 1],
    ['in', 'IFC', 'ㄴ', 'ㅎㅏㄴ', 3, 3, 1],
    ['ce', 'ㄴ', 'ㅎㅏㄴ', 3, 3],
    ['sent', 'ㄴ'],
    ['cs', '', 'ㅎㅏㄴ', 3, 3],
    ['cu', 'ㄱ', 'ㅎㅏㄴ', 3, 3],
    ['bi', 'ICT', 'ㄱ', 'ㅎㅏㄴ', 3, 3, 1],
    ['in', 'ICT', 'ㄱ', 'ㅎㅏㄴㄱ', 3, 4, 1],
    ['kd', 'ㄱ', 229, 'KeyR', '', 1],
    ['ku', 'ㄱ', 82, 'KeyR', '', 1],
    ['cu', '그', 'ㅎㅏㄴㄱ', 3, 4],
    ['bi', 'ICT', '그', 'ㅎㅏㄴㄱ', 3, 4, 1],
    ['in', 'ICT', '그', 'ㅎㅏㄴ그', 3, 4, 1],
    ['kd', 'ㅡ', 229, 'KeyM', '', 1],
    ['ku', 'ㅡ', 77, 'KeyM', '', 1],
    ['cu', '글', 'ㅎㅏㄴ그', 3, 4],
    ['bi', 'ICT', '글', 'ㅎㅏㄴ그', 3, 4, 1],
    ['in', 'ICT', '글', 'ㅎㅏㄴ글', 3, 4, 1],
    ['kd', 'ㄹ', 229, 'KeyF', '', 1],
    ['ku', 'ㄹ', 70, 'KeyF', '', 1],
    ['cu', '글', 'ㅎㅏㄴ글', 3, 4],
    ['bi', 'ICT', '글', 'ㅎㅏㄴ글', 3, 4, 1],
    ['in', 'ICT', '글', 'ㅎㅏㄴ글', 3, 4, 1],
    ['bi', 'DCT', null, 'ㅎㅏㄴ글', 3, 4, 1],
    ['in', 'DCT', null, 'ㅎㅏㄴ', 3, 3, 1],
    ['bi', 'IFC', '글', 'ㅎㅏㄴ', 3, 3, 1],
    ['in', 'IFC', '글', 'ㅎㅏㄴ글', 4, 4, 1],
    ['ce', '글', 'ㅎㅏㄴ글', 4, 4],
    ['sent', '글'],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', 'ㅎㅏㄴ글', 4, 4],
    ['in', 'IT', ' ', 'ㅎㅏㄴ글\u00a0', 5, 5],
    ['ku', ' ', 32, 'Space'],
  ],
  // t_c_safari_xterm2.json — Safari, xterm 5.5: composition events throughout
  t_c_safari_xterm2: [
    ['ku', 'ㅎ', 71, 'KeyG'],
    ['cs', '', '', 0, 0],
    ['cu', 'ㅎ', '', 0, 0],
    ['bi', 'ICT', 'ㅎ', '', 0, 0, 1],
    ['in', 'ICT', 'ㅎ', 'ㅎ', 0, 1, 1],
    ['kd', 'ㅎ', 229, 'KeyG', '', 1],
    ['cu', '하', 'ㅎ', 0, 1],
    ['bi', 'ICT', '하', 'ㅎ', 0, 1, 1],
    ['in', 'ICT', '하', '하', 0, 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK', '', 1],
    ['ku', 'ㅏ', 75, 'KeyK', '', 1],
    ['cu', '한', '하', 0, 1],
    ['bi', 'ICT', '한', '하', 0, 1, 1],
    ['in', 'ICT', '한', '한', 0, 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS', '', 1],
    ['ku', 'ㄴ', 83, 'KeyS', '', 1],
    ['cu', '한', '한', 0, 1],
    ['bi', 'ICT', '한', '한', 0, 1, 1],
    ['in', 'ICT', '한', '한', 0, 1, 1],
    ['bi', 'DCT', null, '한', 0, 1, 1],
    ['in', 'DCT', null, '', 0, 0, 1],
    ['bi', 'IFC', '한', '', 0, 0, 1],
    ['in', 'IFC', '한', '한', 1, 1, 1],
    ['ce', '한', '한', 1, 1],
    ['sent', '한'],
    ['cs', '', '한', 1, 1],
    ['cu', 'ㄱ', '한', 1, 1],
    ['bi', 'ICT', 'ㄱ', '한', 1, 1, 1],
    ['in', 'ICT', 'ㄱ', '한ㄱ', 1, 2, 1],
    ['kd', 'ㄱ', 229, 'KeyR', '', 1],
    ['ku', 'ㄱ', 82, 'KeyR', '', 1],
    ['cu', '그', '한ㄱ', 1, 2],
    ['bi', 'ICT', '그', '한ㄱ', 1, 2, 1],
    ['in', 'ICT', '그', '한그', 1, 2, 1],
    ['kd', 'ㅡ', 229, 'KeyM', '', 1],
    ['ku', 'ㅡ', 77, 'KeyM', '', 1],
    ['cu', '글', '한그', 1, 2],
    ['bi', 'ICT', '글', '한그', 1, 2, 1],
    ['in', 'ICT', '글', '한글', 1, 2, 1],
    ['kd', 'ㄹ', 229, 'KeyF', '', 1],
    ['ku', 'ㄹ', 70, 'KeyF', '', 1],
    ['cu', '글', '한글', 1, 2],
    ['bi', 'ICT', '글', '한글', 1, 2, 1],
    ['in', 'ICT', '글', '한글', 1, 2, 1],
    ['bi', 'DCT', null, '한글', 1, 2, 1],
    ['in', 'DCT', null, '한', 1, 1, 1],
    ['bi', 'IFC', '글', '한', 1, 1, 1],
    ['in', 'IFC', '글', '한글', 2, 2, 1],
    ['ce', '글', '한글', 2, 2],
    ['sent', '글'],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '한글', 2, 2],
    ['in', 'IT', ' ', '한글\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
  ],
  // t_c_safari_fresh_xterm.json — Safari, a fresh xterm 5.5: composition events throughout
  t_c_safari_fresh_xterm: [
    ['cs', '', '', 0, 0],
    ['cu', 'ㅎ', '', 0, 0],
    ['bi', 'ICT', 'ㅎ', '', 0, 0, 1],
    ['in', 'ICT', 'ㅎ', 'ㅎ', 0, 1, 1],
    ['kd', 'ㅎ', 229, 'KeyG', '', 1],
    ['ku', 'ㅎ', 71, 'KeyG', '', 1],
    ['cu', '하', 'ㅎ', 0, 1],
    ['bi', 'ICT', '하', 'ㅎ', 0, 1, 1],
    ['in', 'ICT', '하', '하', 0, 1, 1],
    ['kd', 'ㅏ', 229, 'KeyK', '', 1],
    ['ku', 'ㅏ', 75, 'KeyK', '', 1],
    ['cu', '한', '하', 0, 1],
    ['bi', 'ICT', '한', '하', 0, 1, 1],
    ['in', 'ICT', '한', '한', 0, 1, 1],
    ['kd', 'ㄴ', 229, 'KeyS', '', 1],
    ['ku', 'ㄴ', 83, 'KeyS', '', 1],
    ['cu', '한', '한', 0, 1],
    ['bi', 'ICT', '한', '한', 0, 1, 1],
    ['in', 'ICT', '한', '한', 0, 1, 1],
    ['bi', 'DCT', null, '한', 0, 1, 1],
    ['in', 'DCT', null, '', 0, 0, 1],
    ['bi', 'IFC', '한', '', 0, 0, 1],
    ['in', 'IFC', '한', '한', 1, 1, 1],
    ['ce', '한', '한', 1, 1],
    ['sent', '한'],
    ['cs', '', '한', 1, 1],
    ['cu', 'ㄱ', '한', 1, 1],
    ['bi', 'ICT', 'ㄱ', '한', 1, 1, 1],
    ['in', 'ICT', 'ㄱ', '한ㄱ', 1, 2, 1],
    ['kd', 'ㄱ', 229, 'KeyR', '', 1],
    ['ku', 'ㄱ', 82, 'KeyR', '', 1],
    ['cu', '그', '한ㄱ', 1, 2],
    ['bi', 'ICT', '그', '한ㄱ', 1, 2, 1],
    ['in', 'ICT', '그', '한그', 1, 2, 1],
    ['kd', 'ㅡ', 229, 'KeyM', '', 1],
    ['ku', 'ㅡ', 77, 'KeyM', '', 1],
    ['cu', '글', '한그', 1, 2],
    ['bi', 'ICT', '글', '한그', 1, 2, 1],
    ['in', 'ICT', '글', '한글', 1, 2, 1],
    ['kd', 'ㄹ', 229, 'KeyF', '', 1],
    ['ku', 'ㄹ', 70, 'KeyF', '', 1],
    ['cu', '글', '한글', 1, 2],
    ['bi', 'ICT', '글', '한글', 1, 2, 1],
    ['in', 'ICT', '글', '한글', 1, 2, 1],
    ['bi', 'DCT', null, '한글', 1, 2, 1],
    ['in', 'DCT', null, '한', 1, 1, 1],
    ['bi', 'IFC', '글', '한', 1, 1, 1],
    ['in', 'IFC', '글', '한글', 2, 2, 1],
    ['ce', '글', '한글', 2, 2],
    ['sent', '글'],
    ['kd', ' ', 32, 'Space'],
    ['kp', ' ', 32, 'Space'],
    ['sent', ' '],
    ['bi', 'IT', ' ', '한글', 2, 2],
    ['in', 'IT', ' ', '한글\u00a0', 3, 3],
    ['ku', ' ', 32, 'Space'],
  ],
};
